//
//  HMSUIStrings.swift
//  HMSRoomKit
//
//  Created by Naman Singhal on 16/10/24.
//

import SwiftUI
import Combine
import HMSSDK

public class HMSUIStrings: ObservableObject {
    
    public init() {}
    
    @Published public var you: String = "You"
    @Published public var someone: String = "Someone"
    @Published public var live: String = "LIVE"
    @Published public var youLeftSession: String = "You left the session"
    @Published public var leftByMistake: String = "Left by mistake?"
    @Published public var rejoin: String = "Rejoin"
    
    @Published public var stop: String = "Stop"
    @Published public var retry: String = "Retry"
    @Published public var view: String = "View"
    @Published public var vote: String = "Vote"
    @Published public var answer: String = "Answer"
    
    @Published public var feedbackThakYou: String = "Thank you for your feedback!"
    @Published public var feedbackMessage: String = "Your answers help us improve."
    
    @Published public var enablePermissions: String = "Enable Permissions"
    @Published public var enablePermissionsMessage: String = "Sharing your camera and microphone permissions helps us give you the optimal experience"
    
    @Published public var leave: String = "Leave"
    @Published public var leaveSession: String = "Leave Session"
    @Published public var leaveSessionMessage: String = "Others will continue after you leave. You can join the session again."
    
    @Published public var endSession: String = "End Session"
    @Published public var endSessionMessageStreamPresented: String = "The session and stream will end for everyone. You can’t undo this action."
    @Published public var endSessionMessageStreamNotPresented: String = "The session will end for everyone. You can’t undo this action."
    
    @Published public var volume: String = "Volume"
    @Published public var cancel: String = "Cancel"
    
    @Published public var streamEnded: String = "Stream ended"
    @Published public var streamYetToStart: String = "Stream yet to start"
    
    @Published public var welcome: String = "Welcome!"
    @Published public var description: String = "Description"
    @Published public var sessionEndedMessage: String = "Have a nice day!"
    @Published public var sesionYetToStartMessage: String = "Sit back and relax"
    
    @Published public var speakerSettings: String = "Speaker Settings"
    @Published public var speaker: String = "Speaker"
    @Published public var phone: String = "Phone"
    @Published public var otherDevices: String = "Other devices"
    
    @Published public var name: String = "Name"
    @Published public var changeName: String = "Change Name"
    @Published public var enterName: String = "Enter Name..."
    @Published public var change: String = "Change"
    
    @Published public var errorTitle: String = "Error"
    
    @Published public var joinNow: String = "Join Now"
    @Published public var decline: String = "Decline"
    @Published public var switchRole: String = "Switch Role"
    @Published public var removeParticipant: String = "Remove Participant"
    
    @Published public var joinStageMessage: String = "You’re invited to join the stage"
    @Published public var setupAudioVideoMessage: String = "Setup your audio and video before joining"
    
    @Published public var minimizeYourTile: String = "Minimize Your Tile"
    @Published public var unpinTile: String = "Unpin tile for myself"
    @Published public var pinTile: String = "Pin tile for myself"
    @Published public var spotlightTileRemove: String = "Remove from spotlight for Everyone"
    @Published public var spotlightTileAdd: String = "Spotlight Tile for Everyone"
    
    @Published public var startingLiveStream: String = "Starting live stream..."
    @Published public var raisedHand: String = "raised hand"
    
    @Published public var screen: String = "Screen"
    @Published public var youAreSharingScreen: String = "You are sharing your screen"
    @Published public var stopScreenshare: String = "Stop Screenshare"
    
    @Published public var declineToJoinStage: String = "declined the request to join the stage"
    @Published public var lostInternetConnectReconnecting: String = "You have lost your network connection. Trying to reconnect."
    @Published public var recordingFailedToStart: String = "Recording failed to start"
    
    @Published public var poorConnection: String = "Poor connection"
    @Published public var videoResumeWhenConnectionImproves: String = "The video will resume automatically when the connection improves"
    
    @Published public var bringOnStage: String = "Bring on Stage"
    @Published public var removeFromStage: String = "Remove from Stage"
    @Published public var closedCaptioningEnabled: String = "Closed Captioning enabled for everyone"
    @Published public var closedCaptioningDisabled: String = "Closed Captioning disabled for everyone"
    @Published public var pollNewTitle: String = "started a new"
    @Published public var pollTitle: String = "started a"
    @Published public var pollStr: String = "poll"
    @Published public var quizStr: String = "quiz"
    @Published public var previewGoLiveButtonTitle: String = "Go Live"
    @Published public var oneJoiningTitle: String = "You are the first to join"
    @Published public var otherSingularTitle: String = "other"
    @Published public var otherPluralTitle: String = "others"
    @Published public var inSessionTitle: String = "in session"
    @Published public var toTitle: String = "To"
    @Published public var blockedFromSendingMessageTitle: String = "You’ve been blocked from sending messages"
    @Published public var chatDisabledTitle: String = "Chat disabled."
    @Published public var dmTitle: String = "DM"
    @Published public var groupTitle: String = "Group"
    @Published public var messageOptionsTitle: String = "Message Options"
    @Published public var messagePrivatelyTitle: String = "Message privately"
    @Published public var pinTitle: String = "Pin"
    @Published public var unpinTitle: String = "Unpin"
    @Published public var copyTextTitle: String = "Copy Text"
    @Published public var hideMessagesTitle: String = "Hide for everyone"
    @Published public var chatBlockTitle: String = "Block from Chat"
    @Published public var sendaMessageTitle: String = "Send a message..."
    @Published public var participantListTitle: String = "Participant List"
    @Published public var searchForParticipantsTitle: String = "Search for participants"
    @Published public var tooManyParticipantsTitle: String = "Too many participants"
    @Published public var searchErrorWithMultipleMemebersTitle: String = "With so many participants, our search can't pinpoint the name you're looking for."
    @Published public var viewAllTitle: String = "View All"
    @Published public var startConversationTitle: String = "Start a conversation"
    @Published public var noMessageErrorTitle: String = "There are no messages here yet. Start a conversation by sending a message."
    @Published public var chooseRecipientTitle: String = "Choose a recipient"
    @Published public var sendMessageToTitle: String = "Send message to"
    @Published public var noRecipientYetTitle: String = "No recipient yet"
    @Published public var rolesTitle: String = "Roles"
    @Published public var closedCaptionsCCTitle: String = "Closed Captions (CC)"
    @Published public var enableClosedCaptionsTitle: String = "Enable Closed Captions (CC) for this session?"
    @Published public var closedCaptionsEnabledTitle: String = "Enable for Everyone"
    @Published public var closedCaptionsEnablingTitle: String = "Enabling Closed Captioning for everyone"
    @Published public var closedCaptionsEnableErrorTitle: String = "Failed to enable Closed Captions"
    @Published public var hideForMeTitle: String = "Hide for Me"
    @Published public var showForMeTitle: String = "Show for Me"
    @Published public var closedCaptionsDisabledTitle: String = "Disable for Everyone"
    @Published public var closedCaptionsDisablingTitle: String = "Disabling Closed Captioning for everyone"
    @Published public var closedCaptionsEnableMessage: String = "This will enable Closed Captions for everyone in this room. You can disable it later."
    @Published public var closedCaptionsDisableMessage: String = "This will disable Closed Captions for everyone in this room. You can enable it again."
    @Published public var optionsTitle: String = "Options"
    @Published public var participantsTitle: String = "Participants"
    @Published public var stopSharingScreenTitle: String = "Stop Sharing Screen"
    @Published public var shareScreenTitle: String = "Share Screen"
    @Published public var cancelBeRightBackTitle: String = "Cancel Be Right Back"
    @Published public var beRightBackTitle: String = "Be Right Back"
    @Published public var lowerHandTitle: String = "Lower Hand"
    @Published public var raiseHandTitle: String = "Raise Hand"
    @Published public var handRaisedTitle: String = "Hand Raised"
    @Published public var recordingOnTitle: String = "Recording On"
    @Published public var startRecordingTitle: String = "Start Recording"
    @Published public var pollsAndQuizzesTitle: String = "Polls and Quizzes"
    @Published public var noiseReducedTitle: String = "Noise Reduced"
    @Published public var reduceNoiseTitle: String = "Reduce Noise"
    @Published public var closeWhiteboardTitle: String = "Close Whiteboard"
    @Published public var openWhiteboardTitle: String = "Open Whiteboard"
    @Published public var discontinueSSWhiteboardTitle: String = "Discontinue screenshare to open the whiteboard"
    @Published public var closedCaptionsTitle: String = "Closed Captions"
    @Published public var liveChatTitle: String = "Live chat"
    @Published public var sendMessageTitle: String = "Send a message"
    @Published public var raisedHandTitle: String = "raised hand"
    @Published public var declineJoinStageTitle: String = "declined the request to join the stage"
    @Published public var qualityTitle: String = "Quality"
    @Published public var qualityAutoTitle: String = "Auto"
    @Published public var qualityHighTitle: String = "High"
    @Published public var qualityMediumTitle: String = "Medium"
    @Published public var qualityLowTitle: String = "Low"
    @Published public var submitFeedbackTitle: String = "Submit Feedback"
    @Published public var effectsTitle: String = "Effects"
    @Published public var noEffectTitle: String = "No effect"
    @Published public var blurTitle: String = "Blur"
    @Published public var backgroundTitle: String = "Backgrounds"
    @Published public var getStartedTitle: String = "Get Started"
    @Published public var audioVideoWarningTitle: String = "Setup your audio and video before joining"
    @Published public var optionTitle: String = "Option"
    @Published public var addAnotherQuesTitle: String = "Add another question"
    @Published public var launchTitle: String = "Launch"
    @Published public var okTitle: String = "OK"
    @Published public var questionTitle: String = "QUESTION"
    @Published public var questionTypeTitle: String = "Question Type"
    @Published public var askQuestionTitle: String = "Ask a question"
    @Published public var addOptionTitle: String = "Add an option"
    @Published public var pointWeigthageTitle: String = "Point Weightage"
    @Published public var fillFieldsErrorTitle: String = "Please fill the fields to Save."
    @Published public var selectAnsErrorTItle: String = "Please select an answer for the question."
    @Published public var saveTitle: String = "Save"
    @Published public var editTitle: String = "Edit"
    @Published public var pollSaveError: String = "You need to have at least one saved question to start a poll."
    @Published public var singleChoiceTitle: String = "Single Choice"
    @Published public var multiChoiceTitle: String = "Multiple Choice"
    @Published public var shortAnsTitle: String = "Short Answer"
    @Published public var longAnsTitle: String = "Long Answer"
    @Published public var selectTypeTitle: String = "Select the type you want to continue with"
    @Published public var nameThisTitle: String = "Name this"
    @Published public var hideVoteCountTitle: String = "Hide vote count"
    @Published public var createTitle: String = "Create"
    @Published public var previousTitle: String = "Previous Polls/Quizzes"
    @Published public var nameFieldErrorTitle: String = "Please fill in the name field to Start"
    @Published public var avgTimeTakenTitle: String = "AVG. TIME TAKEN"
    @Published public var avgScoreTitle: String = "AVG. SCORE"
    @Published public var rankTitle: String = "YOUR RANK"
    @Published public var pointsTitle: String = "POINTS"
    @Published public var timeTakenTitle: String = "TIME TAKEN"
    @Published public var correctAnswersTitle: String = "CORRECT ANSWERS"
    @Published public var participationSummaryTitle: String = "Participation Summary"
    @Published public var leaderboardTitle: String = "Leaderboard"
    @Published public var castAnswerMessage: String = "Based on score and time taken to cast the correct answer"
    @Published public var votes: String = "Votes"
    @Published public var votedTitle: String = "Voted"
    @Published public var answeredTitle: String = "Answered"
    @Published public var questionsTitle: String = "Questions"
    @Published public var viewLeaderBoardTitle: String = "View Leaderboard"
    @Published public var endTitle: String = "End"
    @Published public var correctAnsTitle: String = "NO. OF CORRECT\nANSWERS"
    @Published public var incorrectAnsTitle: String = "NO. OF INCORRECT\nANSWERS"
    @Published public var yourAnswerTitle: String = "Your Answer"
    @Published public var switchRoleMessage: String = "Switch the role of"
    @Published public var newMessagesTitle: String = "New messages"
    @Published public var requestUnmuteTitle: String = "Request Unmute"
    @Published public var muteAudioTitle: String = "Mute Audio"
    @Published public var muteVideoTitle: String = "Mute Video"
    @Published public var unmuteVideoTitle: String = "Unmute Video"
    @Published public var watchingTitle: String = "%@ watching"
    @Published public var startedTitle: String = "Started"
    @Published public var agoTitle: String = "ago"
    @Published public var moreTitle: String = "...more"
    @Published public var recordingTitle: String = "Recording"
    @Published public var stopRecordingTitle: String = "Stop Recording"
    @Published public var stopRecordingMessage: String = "Are you sure you want to stop recording? You can’t undo this action."
    @Published public var virtualBGTitle: String = "Virtual Background"
    @Published public var from: String = "from"
    @Published public var my: String = "my"
    @Published public var done: String = "Done"
    @Published public var and: String = "and"
    @Published public var of: String = "of"
    @Published public var pollDraftState: String = "DRAFT"
    @Published public var pollEndedState: String = "ENDED"
    @Published public var everyone: String = "Everyone"
}
